#include "cocoa_time.c"
#include "context.c"
#include "egl_context.c"
#include "glx_context.c"
#include "init.c"
#include "input.c"
#include "linux_joystick.c"
#include "monitor.c"
#include "null_init.c"
#include "null_joystick.c"
#include "null_monitor.c"
#include "null_window.c"
#include "osmesa_context.c"
#include "platform.c"
#include "posix_module.c"
#include "posix_poll.c"
#include "posix_thread.c"
#include "posix_time.c"
#include "vulkan.c"
#include "wgl_context.c"
#include "win32_init.c"
#include "win32_joystick.c"
#include "win32_module.c"
#define fitToMonitor fitToMonitor2
#define acquireMonitor acquireMonitor2
#define releaseMonitor releaseMonitor2
#define createNativeWindow createNativeWindow2
#include "win32_monitor.c"
#include "win32_thread.c"
#include "win32_time.c"
#include "win32_window.c"
#include "window.c"
#include "wl_init.c"
#include "wl_monitor.c"
#include "wl_window.c"
#include "x11_init.c"
#include "x11_monitor.c"
#include "x11_window.c"
#include "xkb_unicode.c"
